#!/bin/bash

# If nothing passed, use the current directory's name as the executable
# (could also look at the cabal file)
TARGET=$1
if [ -z "$1" ]
  then
    TARGET=$(basename `pwd`)
fi

stack build $TARGET && stack exec $TARGET ${@:2}
